[project]
name = "metricviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "hydra-core>=1.3.2",
    "omegaconf>=2.3.0",
    "parse>=1.20.2",
    "plotly>=6.2.0",
    "streamlit>=1.40.1",
    "watchdog>=4.0.2",
]
